### ISSUE TITLE
Rename BuilderInfo.Impl to BuilderInfo.Package

### ISSUE THREAD

**Issue by geeknoid** [istio/old_mixer_repo#1152]
Let's eliminate the non-word "impl" from our API surface. I thought we had that one beat, but it just reared its head again.

**Comment by guptasu** [comment]
Then, let's also do the same replacement for Template.Info object.

**Comment by geeknoid** [comment]
I think we can close this, right?

**Comment by guptasu** [comment]
@geeknoid this is not done and will break the few adapters we have now. It is a simple rename for the adapters so compile time breaking them is not that terrible. However, I personally prefer `impl` because it can be a github link to the implementation code or it can be a package name; `Package` on the other hand is very opinionated.
